### ISSUE TITLE
bad argument

### ISSUE THREAD

**Issue by cipitaua** [v1993/linuxmotehook#8]
on ubuntu-devel I'm trying the latest "bundled" package from this repository and got myself libffi6, as suggested [here](https://github.com/v1993/linuxmotehook/issues/5#issuecomment-823247262),  but I get the following error:

```
$ ./main.lua 
Note: no MotionPlus detected, providen data will be limited to acceleration only
If you have one, it can be hotplugged now

lua5.3: /home/me/Apps/linuxmotehook_0.2.2/wiimote.lua:189: bad argument #1 to 'format' (number expected, got nil)
stack traceback:
        [C]: in function 'string.format'
        /home/me/Apps/linuxmotehook_0.2.2/wiimote.lua:189: in field 'setup'
        ./main.lua:104: in main chunk
        [C]: in ?
```

**Comment by v1993** [comment]
Can you, please, replace

https://github.com/v1993/linuxmotehook/blob/5de1ea5db0952221c6ace95c95bcaadc55f6c825/wiimote.lua#L163

with

```
	desc.mac = common.pathToMac(path); print(path)
```

and post what it prints?

**Comment by cipitaua** [comment]
it additionally prints the following line:

`/sys/devices/pci0000:00/0000:00:14.0/usb1/1-7/1-7:1.0/bluetooth/hci0/hci0:256/0005:057E:0306.006C`

**Comment by v1993** [comment]
Actually, is this fixed if you manually apply change from https://github.com/v1993/linuxmotehook/commit/db3668efa74f5670ddd8637266c0b08339ee8c76? It's not included into latest bundle, I probably should release an update.

**Comment by cipitaua** [comment]
yes it was that, I though latest release was updated. Anyway I get the usual Lgi:ERROR:marshal.c error :(

closing, thank you
